blank_issues_enabled: true
contact_links:
  - name: DevRel Labs Meta Repository
    url: https://github.com/HubSpot/DevRel-Labs-Meta-Repo
    about: For questions about the DevRel Labs program itself
  - name: DevRel Labs Documentation
    url: https://github.com/HubSpot/DevRel-Labs-Meta-Repo/tree/main/docs
    about: Read the DevRel Labs documentation and best practices
